const DEFAULT_PORT = 3000;
const SALT_FACTOR = 10;

const MAX_USERNAME_LENGTH = 20;
const MAX_SUMMARY_LENGTH = 120;
const MAX_DESCRIPTION_LENGTH = 40000;
const MAX_TAG_LABEL_LENGTH = 35;

const ELASTICSEARCH_PING_TIMEOUT = 30000;
const ELASTICSEARCH_SELECT_ALL_LIMIT = 1000;
const ELASTICSEARCH_DEFAULT_DOC_TYPE = '_doc';

module.exports = {
  DEFAULT_PORT,
  SALT_FACTOR,
  MAX_USERNAME_LENGTH,
  MAX_SUMMARY_LENGTH,
  MAX_DESCRIPTION_LENGTH,
  MAX_TAG_LABEL_LENGTH,
  ELASTICSEARCH_PING_TIMEOUT,
  ELASTICSEARCH_SELECT_ALL_LIMIT,
  ELASTICSEARCH_DEFAULT_DOC_TYPE
};
